-- DROP SCHEMA mw_repo;

CREATE SCHEMA mw_repo AUTHORIZATION mwrepo;

-- DROP SEQUENCE mw_repo.credentials_id_seq;

CREATE SEQUENCE mw_repo.credentials_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE mw_repo.credentials_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE mw_repo.credentials_id_seq TO postgres;

-- DROP SEQUENCE mw_repo.server_service_join_id_seq;

CREATE SEQUENCE mw_repo.server_service_join_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE mw_repo.server_service_join_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE mw_repo.server_service_join_id_seq TO postgres;

-- DROP SEQUENCE mw_repo.system_server_join_id_seq;

CREATE SEQUENCE mw_repo.system_server_join_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE mw_repo.system_server_join_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE mw_repo.system_server_join_id_seq TO postgres;
-- mw_repo.credentials definition

-- Drop table

-- DROP TABLE mw_repo.credentials;

CREATE TABLE mw_repo.credentials (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"type" varchar(255) NULL,
	server_ip varchar(255) NULL,
	username varchar(255) NULL,
	"password" varchar(255) NULL,
	service_uri text NULL,
	lifecycle varchar(255) NULL,
	"system" varchar NULL,
	service_type varchar(255) NULL,
	CONSTRAINT credentials_pk PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE mw_repo.credentials OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.credentials TO postgres;


-- mw_repo.lifecycles definition

-- Drop table

-- DROP TABLE mw_repo.lifecycles;

CREATE TABLE mw_repo.lifecycles (
	"type" varchar(255) NOT NULL,
	CONSTRAINT lifecycles_pk PRIMARY KEY (type)
);

-- Permissions

ALTER TABLE mw_repo.lifecycles OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.lifecycles TO postgres;


-- mw_repo.operating_system definition

-- Drop table

-- DROP TABLE mw_repo.operating_system;

CREATE TABLE mw_repo.operating_system (
	"name" varchar(255) NOT NULL,
	vendor varchar(255) NULL,
	supported bool NULL,
	CONSTRAINT operating_system_pk PRIMARY KEY (name)
);

-- Permissions

ALTER TABLE mw_repo.operating_system OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.operating_system TO postgres;


-- mw_repo.servers definition

-- Drop table

-- DROP TABLE mw_repo.servers;

CREATE TABLE mw_repo.servers (
	ip_address varchar(55) NOT NULL,
	hostname varchar(255) NULL,
	full_name varchar(255) NULL,
	"system" varchar(255) NULL,
	os varchar(255) NULL,
	os_version varchar(255) NULL,
	hardware_model varchar(255) NULL,
	lifecycle varchar(255) NULL,
	application varchar(255) NULL,
	is_virtual bool NULL,
	cores int4 NULL,
	memory int8 NULL,
	mac_address varchar(255) NULL,
	hypervisor varchar(255) NULL,
	"location" varchar(255) NULL,
	"comment" text NULL,
	backend varchar(255) NULL,
	dedicated_admin varchar(255) NULL,
	CONSTRAINT servers_pk PRIMARY KEY (ip_address)
);

-- Permissions

ALTER TABLE mw_repo.servers OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.servers TO postgres;


-- mw_repo.services definition

-- Drop table

-- DROP TABLE mw_repo.services;

CREATE TABLE mw_repo.services (
	"name" varchar(255) NOT NULL,
	"type" varchar(255) NULL,
	ip varchar(255) NULL,
	port int4 NULL,
	protocol varchar(255) NULL,
	port_type varchar(255) NULL,
	uri varchar(255) NULL,
	tls_enabled bool NULL,
	certificate text NULL,
	admin_user varchar(255) NULL,
	lifecycle varchar(255) NULL,
	"system" varchar(255) NULL,
	admin_password varchar(255) NULL,
	CONSTRAINT services_pk PRIMARY KEY (name)
);

-- Permissions

ALTER TABLE mw_repo.services OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.services TO postgres;


-- mw_repo."system" definition

-- Drop table

-- DROP TABLE mw_repo."system";

CREATE TABLE mw_repo."system" (
	"type" varchar(255) NOT NULL,
	"comment" text NULL,
	is_in_production bool NOT NULL,
	"name" varchar(255) NOT NULL,
	service_owner varchar(255) NULL,
	shortname varchar(255) NULL,
	vendor varchar(255) NULL,
	product_name varchar(255) NULL,
	CONSTRAINT system_pk PRIMARY KEY (name)
);

-- Permissions

ALTER TABLE mw_repo."system" OWNER TO postgres;
GRANT ALL ON TABLE mw_repo."system" TO postgres;


-- mw_repo.server_service_join definition

-- Drop table

-- DROP TABLE mw_repo.server_service_join;

CREATE TABLE mw_repo.server_service_join (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	server_ip varchar(55) NOT NULL,
	service_name varchar(255) NOT NULL,
	CONSTRAINT server_service_join_pk PRIMARY KEY (id),
	CONSTRAINT server_service_join_servers_fk FOREIGN KEY (server_ip) REFERENCES mw_repo.servers(ip_address),
	CONSTRAINT server_service_join_services_fk FOREIGN KEY (service_name) REFERENCES mw_repo.services("name")
);

-- Permissions

ALTER TABLE mw_repo.server_service_join OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.server_service_join TO postgres;


-- mw_repo.system_server_join definition

-- Drop table

-- DROP TABLE mw_repo.system_server_join;

CREATE TABLE mw_repo.system_server_join (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	server_ip varchar(55) NOT NULL,
	system_name varchar(255) NOT NULL,
	CONSTRAINT system_server_join_pk PRIMARY KEY (id),
	CONSTRAINT system_server_join_servers_fk FOREIGN KEY (server_ip) REFERENCES mw_repo.servers(ip_address),
	CONSTRAINT system_server_join_system_fk FOREIGN KEY (system_name) REFERENCES mw_repo."system"("name")
);

-- Permissions

ALTER TABLE mw_repo.system_server_join OWNER TO postgres;
GRANT ALL ON TABLE mw_repo.system_server_join TO postgres;




-- Permissions

GRANT ALL ON SCHEMA mw_repo TO mwrepo;